name: basd-devel_build

env:
  workdir: /builder

on:
  push:

jobs:
  build-bash:
    runs-on: ubuntu-20.04
    container:
      image: carterjones/manjaro
      volumes:
        - /dev:/dev
      options: --ulimit nofile=1024:10240 --privileged
    timeout-minutes: 720 # timeout 12h
    steps:
      - name: Preserve evn set in the container
        run: |
          echo HOME=/builder >> "$GITHUB_ENV"
          echo PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin >> "$GITHUB_ENV"
      
      - name: Install build dependencies
        shell: bash
        working-directory: ${{ env.workdir }}
        run: |
          sudo pacman -Sy base-devel git tree sudo --noconfirm
      
      - name: Clone repos
        shell: bash
        working-directory: ${{ env.workdir }}
        run: |
          sed -i "s/MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j8\"/g" /etc/makepkg.conf
          su - builder -c "git clone https://github.com/${{ github.repository }}.git -b  ${GITHUB_REF##*/} src"
      
      - name: Build base-devel
        shell: bash
        working-directory: ${{ env.workdir }}/src
        run: |
          su - builder -c "cd /builder/src && makepkg -s PKGBUILD"
      
      - name: Sign
        shell: bash
        working-directory: ${{ env.workdir }}/src
        run: |
          if [ -z "${{ secrets.CALONG_GPG_PRI }}" ] || [ -z "${{ secrets.CALONG_GPG_PASSWD }}" ]; then
              echo "## gpg credentials not provided. Skip signing."
          else
              cat <(echo -e "${{ secrets.CALONG_GPG_PRI }}" | base64 --decode) | gpg --batch --import &>/dev/null
              for p in $(find $PWD -maxdepth 1 -regex '.*\.pkg\.tar\.\(xz\|zst\)'); do
                echo "## signing $p"
                gpg --pinentry-mode loopback --passphrase "${{ secrets.CALONG_GPG_PASSWD }}" --detach-sign ${p}
              done
          fi

      - name: push Pkg
        shell: bash
        working-directory: ${{ env.workdir }}
        run:
          su - builder -c "git clone https://github.com/arch-calong/local_repos.git && git config --global user.name 'just-github' && git config --global user.email 230589406@qq.com && git config --global user.password ${{ secrets.CALONG_PUSH_TOKEN }} && cp ${{ env.workdir }}/src/*.pkg.tar.* ${{ env.workdir }}/local_repos  && cd ${{ env.workdir }}/local_repos && git add ${{ env.workdir }}/local_repos/*tar* && git commit -m 'add base-devel pkg' && git config --list && git push"
      
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ env.workdir }}/src/*.pkg.tar.*
